### PR TITLE
WIP - PayPal Gateway

### PR DESCRIPTION
**Pull request by swelham**
I have started working on the PayPal REST API gateway and wasn't sure if you prefer to merge it into the main repo in stages or as a completed piece of work.

If the latter, then I figured we can leave this PR open and continue to work on it until completion.

### CODE REVIEW

**Comment by joshnuss** [comment]
Excellent.

You can use ActiveMerchant's code as a guide, I've structured everything similarly (where possible).

And I think separate repo might be a good option, always felt it should have been like that in ActiveMerchant, because when all gateways are in one repo it creates a bit of a gatekeeper situation.

Next week I will extract the Stripe gateway to its own repo and possibly write a generator (for creating new gateway repos).

Cheers,

**Comment by swelham** [comment]
I was thinking the same. I originally went to start writing a payment gateway before seeing this project and was going to take that approach.

I will extract the changes made to base core files and submit a separate PR for those and then move the paypal gateway into its own repo and close this PR.

I have an idea that might help speed things up a little, do you use slack, gitter or anything?

**Comment by joshnuss** [comment]
That would be perfect.

You can reach me on skype

**Comment by swelham** [comment]
Perfect, I have sent a contact request.

**Pull request closed without merging**
